/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MedEps.Formularios;


import MedEps.Modelo.Entidades.Enumeraciones.RolUsuarioEnum;
import MedEps.Modelo.Entidades.Usuario;
import java.sql.SQLException;
import java.util.UUID;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Dylan
 */
public class Registro extends javax.swing.JFrame {
        
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        setLocationRelativeTo(this);
        labelEspecialidad.setVisible(false);  // Ocultar el JLabel de especialidad
        textFieldEspecialidad.setVisible(false);  // Ocultar el JTextField de especialidad
        jSeparator7.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNumeroDocumento = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        labelEspecialidad = new javax.swing.JLabel();
        textFieldEspecialidad = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setSize(new java.awt.Dimension(800, 500));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(800, 500));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon.png"))); // NOI18N
        Background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, 40));

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel2.setText("Registro");
        Background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nombre.png"))); // NOI18N
        jLabel3.setText("Nombres");
        Background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        txtNombres.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(60, 60, 60));
        txtNombres.setBorder(null);
        Background.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, 30));
        Background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 210, 10));

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nombre.png"))); // NOI18N
        jLabel4.setText("Apellidos");
        Background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtApellidos.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(70, 70, 70));
        txtApellidos.setBorder(null);
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        Background.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, 20));
        Background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 263, 210, 10));

        cmbTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "T.I", "C.C", "Cedula Extranjeria" }));
        cmbTipoDocumento.setBorder(null);
        Background.add(cmbTipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 120, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carne-de-identidad.png"))); // NOI18N
        jLabel5.setText("Tipo de Documento");
        Background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carpeta.png"))); // NOI18N
        jLabel6.setText("Numero de Documento");
        Background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        txtNumeroDocumento.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtNumeroDocumento.setForeground(new java.awt.Color(70, 70, 70));
        txtNumeroDocumento.setBorder(null);
        Background.add(txtNumeroDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 200, -1));
        Background.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 210, 10));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/hombre.png"))); // NOI18N
        jLabel7.setText("Tipo de usuario");
        Background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "ADMINISTRADOR", "DOCTOR", "PACIENTE", " ", " ", " ", " ", " " }));
        cmbRol.setToolTipText("");
        cmbRol.setBorder(null);
        cmbRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolActionPerformed(evt);
            }
        });
        Background.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/correo-electronico-confidencial.png"))); // NOI18N
        jLabel8.setText("Correo Electronico");
        Background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(70, 70, 70));
        txtCorreo.setBorder(null);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        Background.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 230, -1));
        Background.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 230, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/telefono-movil.png"))); // NOI18N
        jLabel9.setText("Numero de Telefono");
        Background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(70, 70, 70));
        txtTelefono.setBorder(null);
        Background.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 230, -1));
        Background.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 230, 10));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salida.png"))); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Background.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seguro.png"))); // NOI18N
        jLabel10.setText("Contraseña");
        Background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        txtContrasena.setBorder(null);
        Background.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 240, -1));
        Background.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 240, 10));

        labelEspecialidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medical-staff.png"))); // NOI18N
        labelEspecialidad.setText("Especialidad");
        Background.add(labelEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        textFieldEspecialidad.setBorder(null);
        Background.add(textFieldEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 140, -1));
        Background.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 140, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/machine.png"))); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 137, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// Crear el EntityManager desde la unidad de persistencia
    EntityManagerFactory emf = Persistence.createEntityManagerFactory("ConfiguracionBd");
    EntityManager em = emf.createEntityManager();

    try {
        Usuario usuario = new Usuario();

        // Generar un código único (UUID como identificador)
        usuario.setCodigo(UUID.randomUUID().toString());

        // Asignar los valores de los campos
        usuario.setNombres(txtNombres.getText().trim());
        usuario.setApellidos(txtApellidos.getText().trim());
        usuario.setTipoDocumento(cmbTipoDocumento.getSelectedItem().toString());
        usuario.setNumeroDocumento(txtNumeroDocumento.getText().trim());
        usuario.setCorreo(txtCorreo.getText().trim());
        usuario.setTelefono(txtTelefono.getText().trim());
        usuario.setContrasena(txtContrasena.getText().trim());

        // Obtener el rol seleccionado del combo y convertirlo al enum
        String rolSeleccionado = cmbRol.getSelectedItem().toString().toUpperCase();

        try {
            usuario.setRol(RolUsuarioEnum.valueOf(rolSeleccionado));
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(null, "Rol inválido: " + rolSeleccionado);
            return;
        }

        // Persistir en la base de datos
        em.getTransaction().begin();
        em.persist(usuario);
        em.getTransaction().commit();

        JOptionPane.showMessageDialog(null, "Registro exitoso");
         limpiarCampos(); // Limpiar los campos después del registro exitoso
    } catch (Exception e) {
        if (em.getTransaction().isActive()) {
            em.getTransaction().rollback();
        }
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al registrar: " + e.getMessage());
    } finally {
        em.close();
        emf.close();
    }
    

    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           new InicioSesion().setVisible(true);
           this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolActionPerformed
        // TODO add your handling code here:
            // Verificar si el tipo de usuario seleccionado es "Doctor"
      
    }//GEN-LAST:event_cmbRolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JComboBox<String> cmbTipoDocumento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel labelEspecialidad;
    private javax.swing.JTextField textFieldEspecialidad;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumeroDocumento;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables



    private void limpiarCampos() {
    txtNombres.setText("");
    txtApellidos.setText("");
    cmbTipoDocumento.setSelectedIndex(0); // Asume que el primer ítem es la opción por defecto
    txtNumeroDocumento.setText("");
    txtCorreo.setText("");
    txtTelefono.setText("");
    txtContrasena.setText("");
    cmbRol.setSelectedIndex(0); // Asume que el primer ítem es la opción por defecto
    }
}


